---
apiVersion: v1
kind: Service
metadata:
  name: freeradius
  namespace: radius
spec:
  type: ClusterIP
  selector:
    app: freeradius
  ports:
    - port: 1812
      targetPort: 1812
      protocol: UDP
